global using System;
global using System.Text;
global using System.Text.Json;
global using System.Threading.Tasks;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using Microsoft.JSInterop;
global using TableTennisTimer.Components;
global using TableTennisTimer.Models;
global using TableTennisTimer.Services;
global using AlexPiApi.Services;
global using static System.Console;
